language: java
jdk:
  - openjdk8

notifications:
  irc:
    channels:
      - "irc.esper.net#theneweconomy"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true