# The New Economy v0.0.2.4
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TheNewEconomy/TNE-Bukkit
Core:
    
    #Whether or not to enable UUID support(results may vary if turned off).
    UUID: true
    
    #Whether or not players should have different balances, banks, etc in different worlds
    Multiworld: false
    
    #The initial balance for accounts.
    #Will be used if no world-specific configurations are found if multiworld is enabled
    Balance: 200.0

    #Whether or not to shorten money amounts
    #Example: 2100 would be 2.1k
    Shorten: true
    
    #whether or not to enable plugin metrics for TNE
    Metrics: true
    
    #All configurations relating to update checking
    Update:
    
        #Whether or not TNE should check if the server is using the latest build
        Check: true
        
        #Whether or not admins(anyone with perm. node tne.admin) should be notified on login if TNE is outdated.
        Notify: true

    #All configurations relating to the data auto saver
    AutoSaver:

        #Whether or not the auto saver is enabled(will auto save player data)
        Enabled: true

        #The interval at which the auto saver will save data(in seconds)
        Interval: 600
        
    #Currently doesn't work
    #All configurations relating to auctions.
    Auction:
    
        #Whether or not auctions should be muted by default.
        # true - Players will have to type /auction listen <lot> to hear auction announcements
        # false - Players will have to type /auction mute <lot> to not hear auction announcements
        Muted: true
        
        #Whether or not multiple auctions can be run at once
        Multiple: false
        
        #whether or not anti-snipe is enabled
        AntiSnipe: true
        
        #The time in seconds 
        SnipePeriod: 30
        
        #The time in seconds the anti-snipe system should add on
        SnipeTime: 20
        
        #Currently doesn't work
        #Whether or not you can auction items via signs - currently unavailable
        Sign: false
        
        #Currently doesn't work
        #Whether or not you can auction items via commands
        Command: true
        
        #The max amount of items a player can have in the auction queue at one time
        Queued: 5
        
        #Whether or not periodic announcements should be made about the current auction(s)
        Announce: true
        
        #The interval for auction announcements if they're enabled
        Interval: 15
        
        #Whether or not the final <CountdownTime> seconds should be announced.
        Countdown: true
        
        #The time in seconds that should be classified as the final countdown period.
        CountdownTime: 10

    #All configurations relating to currency.
    Currency:
    
        #Whether or not to use the advanced currency system.
        #The advanced currency system allows multiple tiered currencies that can be digital or item-based - currently unavailable
        Advanced: false

        #Would you like to use an item as the currency?
        ItemCurrency: false
        
        #If you want to use an item, which one?(Please use the name of the item)
        #Example: GOLD_INGOT
        ItemMajor: GOLD_INGOT
        
        #The minor item currency item.
        #Example: for USD this might be quarters or dimes
        ItemMinor: IRON_INGOT

        #The name of the major currency
        #Example: Dollars
        MajorName:

            #The singular name. Example: Dollar
            Single: Dollar

            #The plural name. Example: Dollars
            Plural: Dollars
            
        #The name of the minor currency
        #Example: Cents
        MinorName:

            #The singular name. Example: Cent
            Single: Cent

            #The plural name. Example: Cents
            Plural: Cents
            
    #All configurations relating to player death.
    Death:
        
        #Whether or not players who die lose all their money
        Lose: false
        
        #Currently doesn't work
        #Whether or not players who have killed other players have access to their bank for the specified interval
        Robbing: false
        
        #Currently doesn't work
        #The amount of time players have access to the other player's bank if Robbing is enabled(in seconds)
        RobbingInterval: 600


    #All configurations relating to banks.
    Bank:

        #Whether or not banks are enabled.
        Enabled: true

        #Whether or not players can use signs to access their banks.
        Sign: false

        #Whether or not players can use a command to access their banks.
        Command: true
        
        #Whether or not testificates named "Banker" allow access to player banks.
        NPC: false
        
        #Whether or not players can use bank balances to pay dues when personal balance is short.
        Connected: false

        #How much is costs to open a bank account.
        Cost: 20.0

        #The number of rows a bank has.( minimum is 1, maximum is 6)
        #1 row = 9 slots
        Rows: 3

        #All configurations relating to bank gold interest.
        Interest:

            #Whether or not interest is enabled.
            Enabled: false

            #The interest rate in decimal form.
            Rate: 0.2

            #The interval at which interest is gained(in seconds)
            Interval: 1800
            
            
    #All configurations relating to worlds
    World:
       
       #Whether or not changing worlds costs money
       EnableChangeFee: false
       
       #How much it costs to change worlds if ChangeFee is enabled
       ChangeFee: 5.0


    #All configurations relating to the database
    Database:

        #The database type to use. Current options: FlatFile, MySQL, SQLite.
        Type: FlatFile
            
        #The prefix to use for TheNewEconomy MySQL and SQLite Tables
        Prefix: TNE
        
        #Whether or not to backup your database automatically before converting to newer versions of TNE
        Backup: true

        #All configurations relating to the FlatFile Database
        FlatFile:

            #The file to which all the data will be saved
            File: economy.tne
            
        #All configurations relating to the MySQL Database
        MySQL:
            
            #The MySQL host
            Host: localhost
            
            #The MySQL port
            Port: 3306
            
            #The MySQL database
            Database: TheNewEconomy
            
            #Your MySQL user's name
            User: user
            
            #Your MySQL user's password
            Password: password
            
        #All configurations relating to the SQLite Database
        SQLite:
            
            #The SQLite Database File
            File: economy.db