#General Data
name: TheNewEconomy
version: 0.0.2.2
description: A feature-packed Bukkit Economy Plugin.
author: creatorfromhell

#Plugin Data
main: com.github.tnerevival.TNE
softdepend: [Vault]


#Command Data
commands:
   bank:
      description: The base command for all bank-related commands.
   money:
      description: The base command for all money-related commands.
   theneweconomy:
      description: The base command for all The New Economy core commands.
      aliases: tne

permissions:
   tne.*:
      description: Gives access to all TNE commands
      default: op
      children:
         tne.admin.help: true
         tne.admin.reload: true
         tne.bank.help: true
         tne.bank.balance: true
         tne.bank.buy: true
         tne.bank.deposit: true
         tne.bank.price: true
         tne.bank.use: true
         tne.bank.withdraw: true
         tne.money.help: true
         tne.money.balance: true
         tne.money.give: true
         tne.money.pay: true

   tne.admin.*:
      description: Gives access to all TNE Admin Commands and bypasses.
      children:
          tne.admin.help: true
          tne.admin.reload: true
          tne.bypass.bank: true
          tne.bypass.nametag: true
          tne.bypass.world: true
          
   tne.bank.*:
      description: Gives access to all TNE Bank Commands
      children:
         tne.bank.help: true
         tne.bank.balance: true
         tne.bank.buy: true
         tne.bank.deposit: true
         tne.bank.price: true
         tne.bank.use: true
         tne.bank.withdraw: true
         
   tne.bypass.*:
      description: Gives access to all TNE Bypasses
      children:
         tne.bypass.bank: true
         tne.bypass.nametag: true
         tne.bypass.world: true

   tne.money.*:
      description: Gives access to all TNE Money Commands
      children:
         tne.money.help: true
         tne.money.balance: true
         tne.money.give: true
         tne.money.pay: true
         
   tne.sign.*:
      description: Gives access to creating all sign types
      children:
         tne.sign.main: true
         tne.sign.bank: true