# The New Economy v0.1.0.0
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TheNewEconomy/TNE-Bukkit
# To view a commented version of this file, visit https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/resources/config.yml.
Core:
    
    #Whether or not to enable UUID support(results may vary if turned off).
    UUID: true
    
    #Whether or not players should have different balances, banks, etc in different worlds
    Multiworld: false

    #Whether or not to enable plugin metrics. This allows us to know how many servers are running TNE,
    #what TNE version, java version, etc.
    Metrics: true

    #All configurations relating to TNE Modules
    Modules:

        #Whether or not to use TNE Modules
        Enabled: true

    #All configurations relating to the server in general.
    Server:

        #Whether or not to consolidate item-based currencies automatically.
        Consolidate: false

        #The name of this server for data-related purposes. Max length is 100 characters.
        Name: "Main Server"

        #All configurations relating to the server's economy account.
        Account:

            #Whether or not the server account has been enabled.
            Enabled: true

            #The name of the server account. Max length is 100 characters.
            Name: "Server_Account"

            #The starting balance for the server account.
            Balance: 500

        #Configurations relating to third-party support.
        ThirdParty:

            #The prefix used by the Towny plugin to denote town UUIDs
            Town: "town-"

            #The prefix used by the Towny plugin to denote nation UUIDs
            Nation: "nation-"

            #The prefix used by the Factions plugin to denote faction UUIDs
            Faction: "faction-"

    #All configurations relating to TNE commands
    Commands:

        #Whether or not players should be able to use /pay instead of /money pay
        PayShort: true

        #Whether or not players should be able to use /balance instead of /money
        BalanceShort: true

        #Whether or not players should be able to use /baltop instead of /money top
        TopShort: true
    
    #All configurations relating to update checking
    Update:
    
        #Whether or not TNE should check if the server is using the latest build
        Check: true
        
        #Whether or not admins(anyone with perm. node tne.admin) should be notified on login if TNE is outdated.
        Notify: true

    Transactions:

        #The time format to use when displaying transaction history data.
        Format: M, d y

        #The timezone to use for transactions.
        Timezone: US/Eastern

    #All configurations relating to the data auto saver
    AutoSaver:

        #Whether or not the auto saver is enabled(will auto save player data)
        Enabled: true

        #The interval at which the auto saver will save data(in seconds)
        Interval: 600

    #All configurations relating to currency.
    Currency:

        Default:

            #Configurations relating to this TNECurrency's name for formatting purposes. Max length is 100 characters.
            Name:

               #Configurations relating to the major name.
               Major:

                  #The singular form of this TNECurrency's name
                  Single: "Dollar"

                  #The plural form of this TNECurrency's name
                  Plural: "Dollars"

               #Configurations relating to the minor name.
               Minor:

                  #The singular form of this TNECurrency's minor name.
                  Single: "Cent"

                  #The plural form of this TNECurrency's name.
                  Plural: "Cents"

            #The format to use when outputting this TNECurrency into chat.
            #The variables you're able to use here.
            #<symbol> - The TNECurrency's symbol
            #<decimal> - The TNECurrency's decimal.
            #<major> - A combination of the TNECurrency's major amount and name
            #<minor> - A combination of the TNECurrency's minor amount and name
            #<major.name> - The TNECurrency's major name.
            #<minor.name> - The TNECurrency's minor name.
            #<major.amount> - The TNECurrency's major amount.
            #<minor.amount> - The TNECurrency's minor amount.
            #<short.amount> - The TNECurrency's shortened amount.
            #<shorten> - Added to make the outputted value shortened
            # If shortened, it will ignore the value of Format.
            #It's also possible to include all colour variables from messages.yml
            #Example: <major> and <minor>
            Format: <symbol><major.amount><decimal><minor.amount>

            #The maximum balance possible for this currency.
            # Maximum possible value: 900000000000000000000000000000000000
            MaxBalance: 900000000000000000000000000000000000

            #The SI Prefixes used when <shorten> is used for the TNECurrency's format.
            #TNE's default prefixes are based off of the Internation Bureau of Weights and Measures official list.
            #http://www.unitarium.com/si-prefixes along with a few addition shorts for Octillion, Nonillion,
            #and Decillion.
            #The order in which the characters are:
            #Thousand - k
            #Million - M
            #Billion - G
            #Trillion - T
            #Quadrillion - P
            #Quintillion - E
            #Sextillion - Z
            #Septillion - Y
            #Octillion - X
            #Nonillion - W
            #Decillion - V
            Prefixes: 'kMGTPEZYXWV'

            #The initial balance for accounts.
            #Will be used if no world-specific configurations are found if multiworld is enabled
            Balance: 200.0

            #Whether or not this TNECurrency is able to be noted using the note command
            Notable: false

            #Whether or not this TNECurrency is the world's default.
            Default: true

            #The conversion power of this TNECurrency to other currencies.
            #This is based on a decimal conversion system where 1.0 is 100% i.e. the "normal" rate
            Conversion: 1.0

            #The character to use as the symbol for this currency.
            Symbol: '$'

            #The character to use as the decimal place holder.
            Decimal: .

            #The amount of digits to display after the decimal character.
            #The maximum amount of places is 4
            DecimalPlaces: 2

            #Would you like to use an item as the TNECurrency?
            ItemCurrency: false

            #Would you like this TNECurrency to be trackable in chests attached to bank signs?
            BankChest: true

            #Would you like your item TNECurrency balances to also check the player's vault?
            Vault: true

            #Would you like your item TNECurrency balances to also check the player's ender chest?
            EnderChest: true

            #Configurations relating to TNECurrency tiers.
            Tiers:

               #The TNETier, this may be anything, but for organizational purposes it's best to use the singular name.
               One:
                  #The oldtype of TNETier this is(Major, or Minor)
                  Type: 'Major'

                  #The weight of the TNETier. E.X. 20USD would equal 20
                  Weight: 1

                  #Configurations relating to if this TNETier is item-based.
                  Item:

                     #The material used for this item.
                     Material: 'PAPER'

                     #The damage value used for this item. Defaults to 0.
                     Damage: 0

                     #The custom name this item must have in order to be considered currency.
                     Name: 'One'

                     #The lore string this item must have  in order to be considered currency.
                     Lore: 'Server Currency'

                     #All configurations relating to enchantment identification for TNECurrency tiers
                     Enchantments:

                         #The format is Enchantment Name: Enchantment Level, or * for all levels
                         ExampleEnchantment: '*'

                  #Configurations relating to the naming of this TNETier
                  Name:

                     #The singular name of this TNETier.
                     Single: 'Ones'

                     #The plural name of this TNETier.
                     Plural: 'One'

               Penny:

                  Type: 'Minor'

                  Weight: 1

                  #Configurations relating to if this TNETier is item-based.
                  Item:

                     #The material used for this item.
                     Material: 'PAPER'

                     #The damage value used for this item. Defaults to 0.
                     Damage: 0

                     #The custom name this item must have in order to be considered currency.
                     Name: 'Penny'

                     #The lore string this item must have  in order to be considered currency.
                     Lore: 'Server Currency'

                     #All configurations relating to enchantment identification for TNECurrency tiers
                     Enchantments:

                         #The format is Enchantment Name: Enchantment Level, or * for all levels
                         ExampleEnchantment: '*'

                  Name:

                      Single: 'Penny'

                      Plural: 'Pennies'

            #Configurations relating to the major TNETier of TNECurrency
            #Example: Dollars
            Major:

                #Whether or not the major value should be separated every three numeric places.
                Separate: true

                #The separator to use for numeric separation.
                Separator: ','

            #Configurations relating to the minor TNETier of TNECurrency
            #Example: Cents
            Minor:

                #This is used to determine how many of minor it takes to make one major
                Weight: 100
            
            
    #All configurations relating to worlds
    World:
       
       #Whether or not changing worlds costs money
       EnableChangeFee: false
       
       #How much it costs to change worlds if ChangeFee is enabled
       ChangeFee: 5.0


    #All configurations relating to the database
    Database:

        #The database type to use. Current options: FlatFile, MySQL, H2.
        Type: flatfile
            
        #The prefix to use for TheNewEconomy MySQL and H2 Tables
        Prefix: TNE
        
        #Whether or not to backup your database automatically before converting to newer versions of TNE
        Backup: true

        #The file to which all the data will be saved if using a file-based database
        File: Economy

        #All configurations relating to direct SQL transactions
        Transactions:

            #Whether or not to use direct SQL transactions to keep your database updated.
            Use: true

            #Whether or not to cache data
            Cache: true

            #How long(in seconds) until the cached data should be stored
            Update: 600

            
        #All configurations relating to the MySQL Database
        MySQL:
            
            #The MySQL host
            Host: localhost
            
            #The MySQL port
            Port: 3306
            
            #The MySQL database
            Database: TheNewEconomy
            
            #Your MySQL user's name
            User: user
            
            #Your MySQL user's password
            Password: password