#General Data
name: TheNewEconomy
version: 0.1.1.4
description: A modular feature-packed Bukkit Economy Plugin.
author: creatorfromhell
api-version: 1.13

#Plugin Data
main: net.tnemc.core.TNE
softdepend: [PlaceholderAPI, Vault, Essentials, Reserve, Towny, mcMMO, GUIShop]