#General Data
name: TheNewEconomy
version: 0.1.1.5
description: A modular feature-packed Bukkit Economy Plugin.
author: creatorfromhell

#Plugin Data
main: net.tnemc.core.TNE
softdepend: [PlaceholderAPI, Vault, Essentials, Reserve, Towny, mcMMO, GUIShop]