# The New Economy v1.0
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TNERevival/TheNewEconomy/


Core:
    #The initial balance for accounts.
    Balance: 200.0

    #Whether or not to shorten money amounts
    #Example: 2100 would be 2.1 k
    Shorten: true

    #All configurations relating to the data auto saver
    AutoSaver:

        #Whether or not the auto saver is enabled(will auto save player data)
        Enabled: true

        #The interval at which the auto saver will save data(in seconds)
        Interval: 600

    #All configurations relating to currency.
    Currency:

        #The name of the currency.
        Name:

            #The singular name. Example: Dollar
            Single: Dollar

            #The plural name. Example: Dollars
            Plural: Dollars


    #All configurations relating to banks.
    Bank:

        #Whether or not banks are enabled.
        Enabled: true

        #Whether or not players can use signs to access their banks.
        Sign: false

        #Whether or not players can use a command to access their banks.
        Command: true

        #How much is costs to open a bank account.
        Cost: 20.0

        #The number of slots a bank has.(Number of slots must be a multiplication of 9. Minimum is 9, and Maximum is 54)
        Size: 27

        #All configuratiosn relating to bank gold interest.
        Interest:

            #Whether or not interest is enabled.
            Enabled: false

            #The interest rate in decimal form.
            Rate: 0.5

            #The interval at which interest is gained(in seconds)
            Interval: 300


    #All configurations relating to the database
    Database:

        #The database type to use. Current options: FlatFile.
        Type: FlatFile

        #All configurations relating to the FlatFile Database
        FlatFile:

            #The file to which all the data will be saved
            File: economy.tne


    #All configurations relating to mobs.
    Mob:
        
        #Whether or not mobs drop money on death.
        Enabled: true

        #Reward configurations for individual mobs
        Bat:
            Enabled: true
            Reward: 10.00

        Blaze:
            Enabled: true
            Reward: 10.00

        CaveSpider:
            Enabled: true
            Reward: 10.00

        Chicken:
            Enabled: true
            Reward: 10.00

        Cow:
            Enabled: true
            Reward: 10.00

        Creeper:
            Enabled: true
            Reward: 10.00

        EnderDragon:
            Enabled: true
            Reward: 10.00

        Enderman:
            Enabled: true
            Reward: 10.00

        Ghast:
            Enabled: true
            Reward: 10.00

        Horse:
            Enabled: true
            Reward: 10.00

        IronGolem:
            Enabled: true
            Reward: 10.00

        MagmaCube:
            Enabled: true
            Reward: 10.00

        Mooshroom:
            Enabled: true
            Reward: 10.00

        Ocelot:
            Enabled: true
            Reward: 10.00

        Pig:
            Enabled: true
            Reward: 10.00

        Sheep:
            Enabled: true
            Reward: 10.00

        Silverfish:
            Enabled: true
            Reward: 10.00

        Skeleton:
            Enabled: true
            Reward: 10.00

        Slime:
            Enabled: true
            Reward: 10.00

        SnowGolem:
            Enabled: true
            Reward: 10.00

        Spider:
            Enabled: true
            Reward: 10.00

        Squid:
            Enabled: true
            Reward: 10.00

        Villager:
            Enabled: true
            Reward: 10.00

        Witch:
            Enabled: true
            Reward: 10.00

        Wither:
            Enabled: true
            Reward: 10.00

        WitherSkeleton:
            Enabled: true
            Reward: 10.00

        Wolf:
            Enabled: true
            Reward: 10.00

        Zombie:
            Enabled: true
            Reward: 10.00

        ZombiePigman:
            Enabled: true
            Reward: 10.00

        ZombieVillager:
            Enabled: true
            Reward: 10.00