# The New Economy v2.0
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TNERevival/TheNewEconomy/


Core:

    #Whether or not players should have different balances, banks, etc in different worlds
    Multiworld: false
    
    #The initial balance for accounts.
    #Will be used if no world-specific configurations are found if multiworld is enabled
    Balance: 200.0

    #Whether or not to shorten money amounts
    #Example: 2100 would be 2.1 k
    Shorten: true

    #All configurations relating to the data auto saver
    AutoSaver:

        #Whether or not the auto saver is enabled(will auto save player data)
        Enabled: true

        #The interval at which the auto saver will save data(in seconds)
        Interval: 600

    #All configurations relating to currency.
    Currency:

        #Would you like to use an item as the currency?
        ItemCurrency: false
        
        #If you want to use an item, which one?(Please use the name of the item)
        #Example: GOLD_INGOT
        ItemMajor: GOLD_INGOT

        #The name of the currency.
        Name:

            #The singular name. Example: Dollar
            Single: Dollar

            #The plural name. Example: Dollars
            Plural: Dollars


    #All configurations relating to banks.
    Bank:

        #Whether or not banks are enabled.
        Enabled: true

        #Whether or not players can use signs to access their banks.
        Sign: false

        #Whether or not players can use a command to access their banks.
        Command: true

        #How much is costs to open a bank account.
        Cost: 20.0

        #The number of rows a bank has.( minimum is 1, maximum is 6)
        #1 row = 9 slots
        Rows: 3

        #All configurations relating to bank gold interest.
        Interest:

            #Whether or not interest is enabled.
            Enabled: false

            #The interest rate in decimal form.
            Rate: 0.2

            #The interval at which interest is gained(in seconds)
            Interval: 1800
            
            
   #All configurations relating to worlds
   World:
       
       #Whether or not changing worlds costs money
       EnableChangeFee: false
       
       #How much it costs to change worlds if ChangeFee is enabled
       ChangeFee: 5.0


    #All configurations relating to the database
    Database:

        #The database type to use. Current options: FlatFile, MySQL.
        Type: FlatFile

        #All configurations relating to the FlatFile Database
        FlatFile:

            #The file to which all the data will be saved
            File: economy.tne
            
        #All configurations relating to the MySQL Database
        MySQL:
            
            #The MySQL host
            host: localhost
            
            #The MySQL database
            database: TheNewEconomy
            
            #Your MySQL user's name
            user: user
            
            #Your MySQL user's password
            password: password