#General Data
name: TheNewEconomy
version: 1.0
description: The New Economy Bukkit Plugin.
author: creatorfromhell

#Plugin Data
main: com.github.tnerevival.TNE


#Command Data
commands:
   bank:
      description: Bank your items and money.
   money:
      description: The main command for money.