name: Java CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build TNE Core
      run: mvn package --file /TNE/pom.xml
    - name: Build Conversion Module
      run: mvn package --file /TNEConversion/pom.xml
    - name: Build Signs Module
      run: mvn package --file /TNESigns/pom.xml
    - name: Build Mobs Module
      run: mvn package --file /TNEMobs/pom.xml
